insert into Cities (Name) values ('Alexandria');
insert into Cities (Name) values ('Marcovia');
insert into Cities (Name) values ('Monte Aprazível');
insert into Cities (Name) values ('Karagandy');
insert into Cities (Name) values ('Montreuil');
insert into Cities (Name) values ('Suslonger');
insert into Cities (Name) values ('Sypniewo');
insert into Cities (Name) values ('Skellefteå');
insert into Cities (Name) values ('Mamasa');
insert into Cities (Name) values ('Puteaux');
insert into Cities (Name) values ('Slatina');
insert into Cities (Name) values ('Alcácer do Sal');
insert into Cities (Name) values ('Nong Phok');
insert into Cities (Name) values ('Pesnica pri Mariboru');
insert into Cities (Name) values ('Lysychovo');
insert into Cities (Name) values ('Kelo');
insert into Cities (Name) values ('Lesnyye Polyany');
insert into Cities (Name) values ('Chadi');
insert into Cities (Name) values ('Bourail');
insert into Cities (Name) values ('Rudnik');
insert into Cities (Name) values ('Żarki-Letnisko');
insert into Cities (Name) values ('Smolyaninovo');
insert into Cities (Name) values ('Pedro Sánchez');
insert into Cities (Name) values ('Funafuti');
insert into Cities (Name) values ('Miguel Pereira');
insert into Cities (Name) values ('Balun');
insert into Cities (Name) values ('Yuanzhou');
insert into Cities (Name) values ('Jedlová');
insert into Cities (Name) values ('Yanmenguan');
insert into Cities (Name) values ('Shatoja');
insert into Cities (Name) values ('Charlotte');
insert into Cities (Name) values ('Văn Điển');
insert into Cities (Name) values ('Dengteke');
insert into Cities (Name) values ('Zhengcun');
insert into Cities (Name) values ('Turirejo');
insert into Cities (Name) values ('Shuangzhong');
insert into Cities (Name) values ('‘Ayn an Nasr');
insert into Cities (Name) values ('Tacheng');
insert into Cities (Name) values ('Níkaia');
insert into Cities (Name) values ('Perugia');
insert into Cities (Name) values ('Potou');
insert into Cities (Name) values ('Thị Trấn Than Uyên');
insert into Cities (Name) values ('Iperu');
insert into Cities (Name) values ('Esperanza');
insert into Cities (Name) values ('Kentongan');
insert into Cities (Name) values ('Saltpond');
insert into Cities (Name) values ('Golema Rečica');
insert into Cities (Name) values ('Vlkoš');
insert into Cities (Name) values ('San Agustin');
insert into Cities (Name) values ('Burunday');
insert into Cities (Name) values ('Ar Riqqah');
insert into Cities (Name) values ('Oke Mesi');
insert into Cities (Name) values ('Kalkal Barat');
insert into Cities (Name) values ('Belmullet');
insert into Cities (Name) values ('Dan Makham Tia');
insert into Cities (Name) values ('Bera');
insert into Cities (Name) values ('Frankfurt am Main');
insert into Cities (Name) values ('Callanca');
insert into Cities (Name) values ('Hebei');
insert into Cities (Name) values ('Dob');
insert into Cities (Name) values ('Pindamonhangaba');
insert into Cities (Name) values ('Rybatskoye');
insert into Cities (Name) values ('Sicaya');
insert into Cities (Name) values ('Tiberias');
insert into Cities (Name) values ('Kasserine');
insert into Cities (Name) values ('Cauayan');
insert into Cities (Name) values ('Villa Dolores');
insert into Cities (Name) values ('Zhangjiayuan');
insert into Cities (Name) values ('Sangongqiao');
insert into Cities (Name) values ('Kumagaya');
insert into Cities (Name) values ('Tatsunochō-tominaga');
insert into Cities (Name) values ('Norrköping');
insert into Cities (Name) values ('Angoulême');
insert into Cities (Name) values ('Balingoan');
insert into Cities (Name) values ('Bukomansimbi');
insert into Cities (Name) values ('Priboj');
insert into Cities (Name) values ('Oslo');
insert into Cities (Name) values ('Syanno');
insert into Cities (Name) values ('Sulop');
insert into Cities (Name) values ('Ḩājjīābād');
insert into Cities (Name) values ('Sofiyivka');
insert into Cities (Name) values ('Chornobay');
insert into Cities (Name) values ('Gibato');
insert into Cities (Name) values ('Panorama');
insert into Cities (Name) values ('Belene');
insert into Cities (Name) values ('Pregonero');
insert into Cities (Name) values ('Oslob');
insert into Cities (Name) values ('Zhangjiafang');
insert into Cities (Name) values ('Miguel Hidalgo');
insert into Cities (Name) values ('Sutukoba');
insert into Cities (Name) values ('Ariquemes');
insert into Cities (Name) values ('Davao');
insert into Cities (Name) values ('Iraquara');
insert into Cities (Name) values ('Srebrenik');
insert into Cities (Name) values ('Werota');
insert into Cities (Name) values ('Jincheng');
insert into Cities (Name) values ('Hengpi');
insert into Cities (Name) values ('Bafoussam');
insert into Cities (Name) values ('Yumani');
insert into Cities (Name) values ('Tasovčići');
