insert into Cities (Id, Name) values (1, 'Erdu');
insert into Cities (Id, Name) values (2, 'Longaví');
insert into Cities (Id, Name) values (3, 'Shuangtang');
insert into Cities (Id, Name) values (4, 'Bromma');
insert into Cities (Id, Name) values (5, 'Razumnoye');
insert into Cities (Id, Name) values (6, 'Echeng');
insert into Cities (Id, Name) values (7, 'Heyou');
insert into Cities (Id, Name) values (8, 'Rekovac');
insert into Cities (Id, Name) values (9, 'North Cowichan');
insert into Cities (Id, Name) values (10, 'Shelopugino');
insert into Cities (Id, Name) values (11, 'Västerås');
insert into Cities (Id, Name) values (12, 'Maranganí');
insert into Cities (Id, Name) values (13, 'Lynn');
insert into Cities (Id, Name) values (14, 'Berezanka');
insert into Cities (Id, Name) values (15, 'Naga');
insert into Cities (Id, Name) values (16, 'Volodymyrets’');
insert into Cities (Id, Name) values (17, 'Kinh Môn');
insert into Cities (Id, Name) values (18, 'Jose Maria Morelos');
insert into Cities (Id, Name) values (19, 'Boršice');
insert into Cities (Id, Name) values (20, 'Banjarejo');
insert into Cities (Id, Name) values (21, 'Thanh Nê');
insert into Cities (Id, Name) values (22, 'Argostólion');
insert into Cities (Id, Name) values (23, 'Bašaid');
insert into Cities (Id, Name) values (24, 'Privlaka');
insert into Cities (Id, Name) values (25, 'Camagüey');
insert into Cities (Id, Name) values (26, 'Zelenchukskaya');
insert into Cities (Id, Name) values (27, 'Mullagh');
insert into Cities (Id, Name) values (28, 'Tulsa');
insert into Cities (Id, Name) values (29, 'Dehang');
insert into Cities (Id, Name) values (30, 'Sicheng');
insert into Cities (Id, Name) values (31, 'San Jose');
insert into Cities (Id, Name) values (32, 'Novoye Devyatkino');
insert into Cities (Id, Name) values (33, 'San Felipe');
insert into Cities (Id, Name) values (34, 'Ulbroka');
insert into Cities (Id, Name) values (35, 'Eskilstuna');
insert into Cities (Id, Name) values (36, 'Butha-Buthe');
insert into Cities (Id, Name) values (37, 'Siliana');
insert into Cities (Id, Name) values (38, 'Sandia');
insert into Cities (Id, Name) values (39, 'La Esperanza');
insert into Cities (Id, Name) values (40, 'La Purisima');
insert into Cities (Id, Name) values (41, 'Millet');
insert into Cities (Id, Name) values (42, 'Joroan');
insert into Cities (Id, Name) values (43, 'Cendagah');
insert into Cities (Id, Name) values (44, 'Xiaoyangqi');
insert into Cities (Id, Name) values (45, 'Shilin');
insert into Cities (Id, Name) values (46, 'Santa Fé do Sul');
insert into Cities (Id, Name) values (47, 'Uva');
insert into Cities (Id, Name) values (48, 'Sukojember');
insert into Cities (Id, Name) values (49, 'Néa Mákri');
insert into Cities (Id, Name) values (50, 'Keda');
insert into Cities (Id, Name) values (51, 'Mata-Utu');
insert into Cities (Id, Name) values (52, 'Ifanadiana');
insert into Cities (Id, Name) values (53, 'Los Angeles');
insert into Cities (Id, Name) values (54, 'Loukhi');
insert into Cities (Id, Name) values (55, 'Jingmen');
insert into Cities (Id, Name) values (56, 'Bobigny');
insert into Cities (Id, Name) values (57, 'Kilinochchi');
insert into Cities (Id, Name) values (58, 'Pirava');
insert into Cities (Id, Name) values (59, 'Caen');
insert into Cities (Id, Name) values (60, 'Prioso Barat');
insert into Cities (Id, Name) values (61, 'Erjiegou');
insert into Cities (Id, Name) values (62, 'Jitan');
insert into Cities (Id, Name) values (63, 'Samayac');
insert into Cities (Id, Name) values (64, 'Black River');
insert into Cities (Id, Name) values (65, 'Dobrich');
insert into Cities (Id, Name) values (66, 'Paris 17');
insert into Cities (Id, Name) values (67, 'Youlan');
insert into Cities (Id, Name) values (68, 'Cankova');
insert into Cities (Id, Name) values (69, 'Alagoinhas');
insert into Cities (Id, Name) values (70, 'Starigrad');
insert into Cities (Id, Name) values (71, 'Roa');
insert into Cities (Id, Name) values (72, 'Xingbin');
insert into Cities (Id, Name) values (73, 'Los Andes');
insert into Cities (Id, Name) values (74, 'Klatakan');
insert into Cities (Id, Name) values (75, 'Ikaalinen');
insert into Cities (Id, Name) values (76, 'Agustín Codazzi');
insert into Cities (Id, Name) values (77, 'Kamiiso');
insert into Cities (Id, Name) values (78, 'Anaco');
insert into Cities (Id, Name) values (79, 'Wenping');
insert into Cities (Id, Name) values (80, 'Taiyu');
insert into Cities (Id, Name) values (81, 'San Silvestre');
insert into Cities (Id, Name) values (82, 'Nisí');
insert into Cities (Id, Name) values (83, 'Huji');
insert into Cities (Id, Name) values (84, 'Shangfang');
insert into Cities (Id, Name) values (85, 'Lexington');
insert into Cities (Id, Name) values (86, 'San Casimiro');
insert into Cities (Id, Name) values (87, 'Qianjiang');
insert into Cities (Id, Name) values (88, 'Tercena');
insert into Cities (Id, Name) values (89, 'Yuyue');
insert into Cities (Id, Name) values (90, 'Golem');
insert into Cities (Id, Name) values (91, 'Grecheskoye');
insert into Cities (Id, Name) values (92, 'Banjar Sembunggede');
insert into Cities (Id, Name) values (93, 'Chaniá');
insert into Cities (Id, Name) values (94, 'Odolanów');
insert into Cities (Id, Name) values (95, 'El Cocuy');
insert into Cities (Id, Name) values (96, 'Grand Rapids');
insert into Cities (Id, Name) values (97, 'Polos');
insert into Cities (Id, Name) values (98, 'Baki');
insert into Cities (Id, Name) values (99, 'Ban Rangsit');
insert into Cities (Id, Name) values (100, 'Morazán');
insert into Cities (Id, Name) values (101, 'Vukovije Donje');
insert into Cities (Id, Name) values (102, 'Khirdalan');
insert into Cities (Id, Name) values (103, 'Xiaoduchuan');
insert into Cities (Id, Name) values (104, 'Noenoni');
insert into Cities (Id, Name) values (105, 'Irákleion');
insert into Cities (Id, Name) values (106, 'Guruyan');
insert into Cities (Id, Name) values (107, 'Nganane');
insert into Cities (Id, Name) values (108, 'San Juan');
insert into Cities (Id, Name) values (109, 'Rtyně v Podkrkonoší');
insert into Cities (Id, Name) values (110, 'Bechyně');
insert into Cities (Id, Name) values (111, 'Lingbei');
insert into Cities (Id, Name) values (112, 'Babushkin');
insert into Cities (Id, Name) values (113, 'Dahay');
insert into Cities (Id, Name) values (114, 'Yongning');
insert into Cities (Id, Name) values (115, 'El Aguacate');
insert into Cities (Id, Name) values (116, 'Tarascon');
insert into Cities (Id, Name) values (117, 'Amsterdam-Oost');
insert into Cities (Id, Name) values (118, 'Luqiao');
insert into Cities (Id, Name) values (119, 'Escada');
insert into Cities (Id, Name) values (120, 'Évry');
insert into Cities (Id, Name) values (121, 'Alexandria');
insert into Cities (Id, Name) values (122, 'Lombog');
insert into Cities (Id, Name) values (123, 'Jinja');
insert into Cities (Id, Name) values (124, 'Altay sumu');
insert into Cities (Id, Name) values (125, 'Studená');
insert into Cities (Id, Name) values (126, 'Agbor');
insert into Cities (Id, Name) values (127, 'Banatsko Veliko Selo');
insert into Cities (Id, Name) values (128, 'Gorodets');
insert into Cities (Id, Name) values (129, 'Węgorzyno');
insert into Cities (Id, Name) values (130, 'Sulo');
insert into Cities (Id, Name) values (131, 'Hassi Berkane');
insert into Cities (Id, Name) values (132, 'Kohlu');
insert into Cities (Id, Name) values (133, 'Tianchi');
insert into Cities (Id, Name) values (134, 'Cuba');
insert into Cities (Id, Name) values (135, 'Cujillo');
insert into Cities (Id, Name) values (136, 'Arvayheer');
insert into Cities (Id, Name) values (137, 'Rio Largo');
insert into Cities (Id, Name) values (138, 'Berck');
insert into Cities (Id, Name) values (139, 'Liuji');
insert into Cities (Id, Name) values (140, 'Stalbe');
insert into Cities (Id, Name) values (141, 'Conroe');
insert into Cities (Id, Name) values (142, 'João Alfredo');
insert into Cities (Id, Name) values (143, 'Níkiti');
insert into Cities (Id, Name) values (144, 'Alvand');
insert into Cities (Id, Name) values (145, 'Svetlyy');
insert into Cities (Id, Name) values (146, 'Loo');
insert into Cities (Id, Name) values (147, 'Narol');
insert into Cities (Id, Name) values (148, 'Graz');
insert into Cities (Id, Name) values (149, 'Pampas');
insert into Cities (Id, Name) values (150, 'Aracaju');
insert into Cities (Id, Name) values (151, 'Jiuhua');
insert into Cities (Id, Name) values (152, 'Hazlov');
insert into Cities (Id, Name) values (153, 'Shuangjie');
insert into Cities (Id, Name) values (154, 'Krugersdorp');
insert into Cities (Id, Name) values (155, 'La Estancia');
insert into Cities (Id, Name) values (156, 'Quanxi');
insert into Cities (Id, Name) values (157, 'Casal Novo');
insert into Cities (Id, Name) values (158, 'Haramgai');
insert into Cities (Id, Name) values (159, 'Galtek');
insert into Cities (Id, Name) values (160, 'Tetebatu');
insert into Cities (Id, Name) values (161, 'Cinangka');
insert into Cities (Id, Name) values (162, 'Kauswagan');
insert into Cities (Id, Name) values (163, 'Rancharia');
insert into Cities (Id, Name) values (164, 'Watodei');
insert into Cities (Id, Name) values (165, 'Petrolera');
insert into Cities (Id, Name) values (166, 'Tarbes');
insert into Cities (Id, Name) values (167, 'Jingnao');
insert into Cities (Id, Name) values (168, 'Ganzhou');
insert into Cities (Id, Name) values (169, 'Kuala Terengganu');
insert into Cities (Id, Name) values (170, 'Milaor');
insert into Cities (Id, Name) values (171, 'Tocota');
insert into Cities (Id, Name) values (172, 'Tampakan');
insert into Cities (Id, Name) values (173, 'Krajan');
insert into Cities (Id, Name) values (174, 'New York City');
insert into Cities (Id, Name) values (175, 'Fresno');
insert into Cities (Id, Name) values (176, 'Perstorp');
insert into Cities (Id, Name) values (177, 'Västervik');
insert into Cities (Id, Name) values (178, 'Meylan');
insert into Cities (Id, Name) values (179, 'Beishan');
insert into Cities (Id, Name) values (180, 'Lagoa de Albufeira');
insert into Cities (Id, Name) values (181, 'Danxi');
insert into Cities (Id, Name) values (182, 'Luntas');
insert into Cities (Id, Name) values (183, 'Patayac');
insert into Cities (Id, Name) values (184, 'Wates');
insert into Cities (Id, Name) values (185, 'Wasquehal');
insert into Cities (Id, Name) values (186, 'Beslan');
insert into Cities (Id, Name) values (187, 'Mostek');
insert into Cities (Id, Name) values (188, 'Tilmi');
insert into Cities (Id, Name) values (189, 'Konduga');
insert into Cities (Id, Name) values (190, 'Ludishan');
insert into Cities (Id, Name) values (191, 'Energeticheskiy');
insert into Cities (Id, Name) values (192, 'Bachok');
insert into Cities (Id, Name) values (193, 'Shanglaxiu');
insert into Cities (Id, Name) values (194, 'Masoli');
insert into Cities (Id, Name) values (195, 'Tambopata');
insert into Cities (Id, Name) values (196, 'Graikochóri');
insert into Cities (Id, Name) values (197, 'Yuantan');
insert into Cities (Id, Name) values (198, 'Airmata');
insert into Cities (Id, Name) values (199, 'Lebahseri');
insert into Cities (Id, Name) values (200, 'Luzhou');
insert into Cities (Id, Name) values (201, 'Pylaía');
insert into Cities (Id, Name) values (202, 'Sovetskaya');
insert into Cities (Id, Name) values (203, 'Loureiro');
insert into Cities (Id, Name) values (204, 'Ciawitali');
insert into Cities (Id, Name) values (205, 'Morrinhos');
insert into Cities (Id, Name) values (206, 'Batasan');
insert into Cities (Id, Name) values (207, 'Grand Rapids');
insert into Cities (Id, Name) values (208, 'Miaotang');
insert into Cities (Id, Name) values (209, 'Dessalines');
insert into Cities (Id, Name) values (210, 'Czarna Białostocka');
insert into Cities (Id, Name) values (211, 'Shizong');
insert into Cities (Id, Name) values (212, 'Chōfugaoka');
insert into Cities (Id, Name) values (213, 'Goodlands');
insert into Cities (Id, Name) values (214, 'Priargunsk');
insert into Cities (Id, Name) values (215, 'Nizhniy Kurkuzhin');
insert into Cities (Id, Name) values (216, 'Shancheng');
insert into Cities (Id, Name) values (217, 'Ar Rifā‘');
insert into Cities (Id, Name) values (218, 'Mikhaylovsk');
insert into Cities (Id, Name) values (219, 'Aranas Sur');
insert into Cities (Id, Name) values (220, 'Ust’-Ulagan');
insert into Cities (Id, Name) values (221, 'Gaspar');
insert into Cities (Id, Name) values (222, 'Laohekou');
insert into Cities (Id, Name) values (223, 'Kozakai-chō');
insert into Cities (Id, Name) values (224, 'Jarošov nad Nežárkou');
insert into Cities (Id, Name) values (225, 'Kabul');
insert into Cities (Id, Name) values (226, 'Inongo');
insert into Cities (Id, Name) values (227, 'Miryang');
insert into Cities (Id, Name) values (228, 'Banjar Penyalin');
insert into Cities (Id, Name) values (229, 'Flen');
insert into Cities (Id, Name) values (230, 'Shangma');
insert into Cities (Id, Name) values (231, 'Kedungbang');
insert into Cities (Id, Name) values (232, 'Gegernoong');
insert into Cities (Id, Name) values (233, 'Nangkaruka');
insert into Cities (Id, Name) values (234, 'Muroto-misakicho');
insert into Cities (Id, Name) values (235, 'Ngangguk');
insert into Cities (Id, Name) values (236, 'Sitovo');
insert into Cities (Id, Name) values (237, 'Znamenka');
insert into Cities (Id, Name) values (238, 'Estefania');
insert into Cities (Id, Name) values (239, 'Vessada');
insert into Cities (Id, Name) values (240, 'Litian');
insert into Cities (Id, Name) values (241, 'Ypacarai');
insert into Cities (Id, Name) values (242, 'Tanniu');
insert into Cities (Id, Name) values (243, 'Vodstroy');
insert into Cities (Id, Name) values (244, 'Úštěk');
insert into Cities (Id, Name) values (245, 'Monteros');
insert into Cities (Id, Name) values (246, 'Tianfen');
insert into Cities (Id, Name) values (247, 'Miragoâne');
insert into Cities (Id, Name) values (248, 'Krajan');
insert into Cities (Id, Name) values (249, 'Tegalrejo');
insert into Cities (Id, Name) values (250, 'Mujur Satu');
insert into Cities (Id, Name) values (251, 'Owode');
insert into Cities (Id, Name) values (252, 'Sol’tsy');
insert into Cities (Id, Name) values (253, 'Huaqiao');
insert into Cities (Id, Name) values (254, 'Rungis');
insert into Cities (Id, Name) values (255, 'Da Nang');
insert into Cities (Id, Name) values (256, 'Mouriscas');
insert into Cities (Id, Name) values (257, 'Opatówek');
insert into Cities (Id, Name) values (258, 'Oele');
insert into Cities (Id, Name) values (259, 'Jojoima');
insert into Cities (Id, Name) values (260, 'Santa Catalina - Dique Lujan');
insert into Cities (Id, Name) values (261, 'Suchedniów');
insert into Cities (Id, Name) values (262, 'Yipeng');
insert into Cities (Id, Name) values (263, 'Málaga');
insert into Cities (Id, Name) values (264, 'Slavyansk-na-Kubani');
insert into Cities (Id, Name) values (265, 'Huayan');
insert into Cities (Id, Name) values (266, 'General Alvear');
insert into Cities (Id, Name) values (267, 'Canggou');
insert into Cities (Id, Name) values (268, 'Kalodzishchy');
insert into Cities (Id, Name) values (269, 'Mawu');
insert into Cities (Id, Name) values (270, 'Santa Luċija');
insert into Cities (Id, Name) values (271, 'Xiayang');
insert into Cities (Id, Name) values (272, 'Jiancha');
insert into Cities (Id, Name) values (273, 'Loncoche');
insert into Cities (Id, Name) values (274, 'Libochovice');
insert into Cities (Id, Name) values (275, 'Mulifanua');
insert into Cities (Id, Name) values (276, 'Wujing');
insert into Cities (Id, Name) values (277, 'Liufang');
insert into Cities (Id, Name) values (278, 'Téra');
insert into Cities (Id, Name) values (279, 'Tangwei');
insert into Cities (Id, Name) values (280, 'Balaoang');
insert into Cities (Id, Name) values (281, 'Boston');
insert into Cities (Id, Name) values (282, 'Campo Maior');
insert into Cities (Id, Name) values (283, 'Ivoti');
insert into Cities (Id, Name) values (284, 'Kyzylorda');
insert into Cities (Id, Name) values (285, 'Đà Bắc');
insert into Cities (Id, Name) values (286, 'Jojoima');
insert into Cities (Id, Name) values (287, 'Springbok');
insert into Cities (Id, Name) values (288, 'Jishu');
insert into Cities (Id, Name) values (289, 'Luohuang');
insert into Cities (Id, Name) values (290, 'Praia Grande');
insert into Cities (Id, Name) values (291, 'Ljungsbro');
insert into Cities (Id, Name) values (292, 'Kristianstad');
insert into Cities (Id, Name) values (293, 'Mukayrās');
insert into Cities (Id, Name) values (294, 'Presidente Bernardes');
insert into Cities (Id, Name) values (295, 'Labo');
insert into Cities (Id, Name) values (296, 'Al Khāniq');
insert into Cities (Id, Name) values (297, 'Molodohvardiys’k');
insert into Cities (Id, Name) values (298, 'Niitsu-honchō');
insert into Cities (Id, Name) values (299, 'Dębica');
insert into Cities (Id, Name) values (300, 'Luotang');
insert into Cities (Id, Name) values (301, 'Jichang');
insert into Cities (Id, Name) values (302, 'Buđanovci');
insert into Cities (Id, Name) values (303, 'Wenqiao');
insert into Cities (Id, Name) values (304, 'Sumbergebang');
insert into Cities (Id, Name) values (305, 'Hitachi-Naka');
insert into Cities (Id, Name) values (306, 'Dambarta');
insert into Cities (Id, Name) values (307, 'Paraná');
insert into Cities (Id, Name) values (308, 'Cové');
insert into Cities (Id, Name) values (309, 'Des Moines');
insert into Cities (Id, Name) values (310, 'La Suiza');
insert into Cities (Id, Name) values (311, 'Fier-Çifçi');
insert into Cities (Id, Name) values (312, 'Kudara-Somon');
insert into Cities (Id, Name) values (313, 'Örebro');
insert into Cities (Id, Name) values (314, 'Falun');
insert into Cities (Id, Name) values (315, 'Xiangyang');
insert into Cities (Id, Name) values (316, 'Zarechnyy');
insert into Cities (Id, Name) values (317, 'Huoqiu Chengguanzhen');
insert into Cities (Id, Name) values (318, 'Issy-les-Moulineaux');
insert into Cities (Id, Name) values (319, 'Lagoa Santa');
insert into Cities (Id, Name) values (320, 'Kamalaputi');
insert into Cities (Id, Name) values (321, 'Yanggang');
insert into Cities (Id, Name) values (322, 'Sinarharapan');
insert into Cities (Id, Name) values (323, 'Caieiras');
insert into Cities (Id, Name) values (324, 'Granica');
insert into Cities (Id, Name) values (325, 'Stepnogorsk');
insert into Cities (Id, Name) values (326, 'Mawang');
insert into Cities (Id, Name) values (327, 'Brzozów');
insert into Cities (Id, Name) values (328, 'San Silvestre');
insert into Cities (Id, Name) values (329, 'Valledupar');
insert into Cities (Id, Name) values (330, 'Srubec');
insert into Cities (Id, Name) values (331, 'Matango');
insert into Cities (Id, Name) values (332, 'Krajan Baru');
insert into Cities (Id, Name) values (333, 'La Courneuve');
insert into Cities (Id, Name) values (334, 'Lālmohan');
insert into Cities (Id, Name) values (335, 'Stockholm');
insert into Cities (Id, Name) values (336, 'Ulaanbaatar');
insert into Cities (Id, Name) values (337, 'Donim');
insert into Cities (Id, Name) values (338, 'Sindangrasa');
insert into Cities (Id, Name) values (339, 'Rakitovo');
insert into Cities (Id, Name) values (340, 'Mamoudzou');
insert into Cities (Id, Name) values (341, 'Okpoga');
insert into Cities (Id, Name) values (342, 'Cihaladan');
insert into Cities (Id, Name) values (343, 'Tanzhou');
insert into Cities (Id, Name) values (344, 'Manevychi');
insert into Cities (Id, Name) values (345, 'Bakhmach');
insert into Cities (Id, Name) values (346, 'Lubbock');
insert into Cities (Id, Name) values (347, 'Nova Viçosa');
insert into Cities (Id, Name) values (348, 'Huiyuan');
insert into Cities (Id, Name) values (349, 'Bhamdoun');
insert into Cities (Id, Name) values (350, 'Lanas');
insert into Cities (Id, Name) values (351, 'Saijō');
insert into Cities (Id, Name) values (352, 'Lüyang');
insert into Cities (Id, Name) values (353, 'Novi Sad');
insert into Cities (Id, Name) values (354, 'Tobilolong');
insert into Cities (Id, Name) values (355, 'Semiluki');
insert into Cities (Id, Name) values (356, 'Gamboula');
insert into Cities (Id, Name) values (357, 'Lunang');
insert into Cities (Id, Name) values (358, 'Panambi');
insert into Cities (Id, Name) values (359, 'Sirājganj');
insert into Cities (Id, Name) values (360, 'Porto Formoso');
insert into Cities (Id, Name) values (361, 'Sarongan');
insert into Cities (Id, Name) values (362, 'Solnechnoye');
insert into Cities (Id, Name) values (363, 'Radoboj');
insert into Cities (Id, Name) values (364, 'Zunilito');
insert into Cities (Id, Name) values (365, 'Motygino');
insert into Cities (Id, Name) values (366, 'Shancheng');
insert into Cities (Id, Name) values (367, 'Łąka Prudnicka');
insert into Cities (Id, Name) values (368, 'Tacheng');
insert into Cities (Id, Name) values (369, 'Kuanchuan');
insert into Cities (Id, Name) values (370, 'Tul’chyn');
insert into Cities (Id, Name) values (371, 'Melgar');
insert into Cities (Id, Name) values (372, 'Il’inskiy');
insert into Cities (Id, Name) values (373, 'São José dos Campos');
insert into Cities (Id, Name) values (374, 'Midland');
insert into Cities (Id, Name) values (375, 'Kutloanong');
insert into Cities (Id, Name) values (376, 'Haarlem');
insert into Cities (Id, Name) values (377, 'Jiangwei');
insert into Cities (Id, Name) values (378, 'Qinā');
insert into Cities (Id, Name) values (379, 'Banān');
insert into Cities (Id, Name) values (380, 'Uzda');
insert into Cities (Id, Name) values (381, 'Lugulu');
insert into Cities (Id, Name) values (382, 'Tála');
insert into Cities (Id, Name) values (383, 'Aksha');
insert into Cities (Id, Name) values (384, 'Salamanca');
insert into Cities (Id, Name) values (385, 'Kalinkavichy');
insert into Cities (Id, Name) values (386, 'San Isidro');
insert into Cities (Id, Name) values (387, 'Raków');
insert into Cities (Id, Name) values (388, 'Santa Fe');
insert into Cities (Id, Name) values (389, 'La Condamine');
insert into Cities (Id, Name) values (390, 'Beidao');
insert into Cities (Id, Name) values (391, 'Seremban');
insert into Cities (Id, Name) values (392, 'Shināş');
insert into Cities (Id, Name) values (393, 'Isojoki');
insert into Cities (Id, Name) values (394, 'Tūkrah');
insert into Cities (Id, Name) values (395, 'Amphoe Sikhiu');
insert into Cities (Id, Name) values (396, 'Soisy-sous-Montmorency');
insert into Cities (Id, Name) values (397, 'Huangliu');
insert into Cities (Id, Name) values (398, 'Paltamo');
insert into Cities (Id, Name) values (399, 'Shuangfeng');
insert into Cities (Id, Name) values (400, 'Wuxia');
insert into Cities (Id, Name) values (401, 'Washington');
insert into Cities (Id, Name) values (402, 'Engenho');
insert into Cities (Id, Name) values (403, 'Huoshaodian');
insert into Cities (Id, Name) values (404, 'Vysoké Mýto');
insert into Cities (Id, Name) values (405, 'Ladoang');
insert into Cities (Id, Name) values (406, 'Oyam');
insert into Cities (Id, Name) values (407, 'Dolega District');
insert into Cities (Id, Name) values (408, 'Ambulong');
insert into Cities (Id, Name) values (409, 'Dolod');
insert into Cities (Id, Name) values (410, 'Chishui');
insert into Cities (Id, Name) values (411, 'Malinta');
insert into Cities (Id, Name) values (412, 'Paurito');
insert into Cities (Id, Name) values (413, 'Alor Setar');
insert into Cities (Id, Name) values (414, 'Bollnäs');
insert into Cities (Id, Name) values (415, 'Ballitoville');
insert into Cities (Id, Name) values (416, 'Owerri');
insert into Cities (Id, Name) values (417, 'Anastácio');
insert into Cities (Id, Name) values (418, 'Khombole');
insert into Cities (Id, Name) values (419, 'Jiangdulu');
insert into Cities (Id, Name) values (420, 'Stráž nad Nisou');
insert into Cities (Id, Name) values (421, 'La Esperanza');
insert into Cities (Id, Name) values (422, 'Puyo');
insert into Cities (Id, Name) values (423, 'Ceper');
insert into Cities (Id, Name) values (424, 'Datagon');
insert into Cities (Id, Name) values (425, 'Kokterek');
insert into Cities (Id, Name) values (426, 'Amqui');
insert into Cities (Id, Name) values (427, 'Ar Rawḑah');
insert into Cities (Id, Name) values (428, 'Aricagua');
insert into Cities (Id, Name) values (429, 'Yumaguzino');
insert into Cities (Id, Name) values (430, 'Pīrgaaj');
insert into Cities (Id, Name) values (431, 'Soest');
insert into Cities (Id, Name) values (432, 'Kandangan');
insert into Cities (Id, Name) values (433, 'Bogovarovo');
insert into Cities (Id, Name) values (434, 'Abuko');
insert into Cities (Id, Name) values (435, 'Samburat');
insert into Cities (Id, Name) values (436, 'Issy-les-Moulineaux');
insert into Cities (Id, Name) values (437, 'Kota Kinabalu');
insert into Cities (Id, Name) values (438, 'Kolirerek');
insert into Cities (Id, Name) values (439, 'Garango');
insert into Cities (Id, Name) values (440, 'San Jacinto');
insert into Cities (Id, Name) values (441, 'Presidente Dutra');
insert into Cities (Id, Name) values (442, 'Shiqian');
insert into Cities (Id, Name) values (443, 'Jiaoxie');
insert into Cities (Id, Name) values (444, 'Shijing');
insert into Cities (Id, Name) values (445, 'Guadalupe');
insert into Cities (Id, Name) values (446, 'Kasese');
insert into Cities (Id, Name) values (447, 'Antipolo');
insert into Cities (Id, Name) values (448, 'Xinzhai');
insert into Cities (Id, Name) values (449, 'Parys');
insert into Cities (Id, Name) values (450, 'Kiełczów');
insert into Cities (Id, Name) values (451, 'Donghu');
insert into Cities (Id, Name) values (452, 'Yelan’');
insert into Cities (Id, Name) values (453, 'Logroño');
insert into Cities (Id, Name) values (454, 'Ulsan');
insert into Cities (Id, Name) values (455, 'Sonorejo');
insert into Cities (Id, Name) values (456, 'La Reforma');
insert into Cities (Id, Name) values (457, 'Datian');
insert into Cities (Id, Name) values (458, 'Balaka');
insert into Cities (Id, Name) values (459, 'Chuanxi');
insert into Cities (Id, Name) values (460, 'Butwāl');
insert into Cities (Id, Name) values (461, 'Bouaflé');
insert into Cities (Id, Name) values (462, 'Rasi Salai');
insert into Cities (Id, Name) values (463, 'Roma');
insert into Cities (Id, Name) values (464, 'Thành Phố Nam Định');
insert into Cities (Id, Name) values (465, 'Jaworzyna Śląska');
insert into Cities (Id, Name) values (466, 'Jonava');
insert into Cities (Id, Name) values (467, 'Megion');
insert into Cities (Id, Name) values (468, 'Nizhyn');
insert into Cities (Id, Name) values (469, 'Tha Luang');
insert into Cities (Id, Name) values (470, 'Dazu');
insert into Cities (Id, Name) values (471, 'Arauca');
insert into Cities (Id, Name) values (472, 'Göteborg');
insert into Cities (Id, Name) values (473, 'Berlin');
insert into Cities (Id, Name) values (474, 'Independencia');
insert into Cities (Id, Name) values (475, 'Astromil');
insert into Cities (Id, Name) values (476, 'Vuhlehirs’k');
insert into Cities (Id, Name) values (477, 'Yangshuo');
insert into Cities (Id, Name) values (478, 'Midland');
insert into Cities (Id, Name) values (479, 'Martapura');
insert into Cities (Id, Name) values (480, 'Mamanguape');
insert into Cities (Id, Name) values (481, 'Capissayan Sur');
insert into Cities (Id, Name) values (482, 'Puerto Colombia');
insert into Cities (Id, Name) values (483, 'Dakingari');
insert into Cities (Id, Name) values (484, 'Erhe');
insert into Cities (Id, Name) values (485, 'Chigasaki');
insert into Cities (Id, Name) values (486, 'Zhiryatino');
insert into Cities (Id, Name) values (487, 'Liwonde');
insert into Cities (Id, Name) values (488, 'Sukasetia');
insert into Cities (Id, Name) values (489, 'Qingshan');
insert into Cities (Id, Name) values (490, 'Molde');
insert into Cities (Id, Name) values (491, 'Quitilipi');
insert into Cities (Id, Name) values (492, 'Hashtpar');
insert into Cities (Id, Name) values (493, 'Innoshima');
insert into Cities (Id, Name) values (494, 'Koina');
insert into Cities (Id, Name) values (495, 'Núi Sập');
insert into Cities (Id, Name) values (496, 'Santa Maria');
insert into Cities (Id, Name) values (497, 'Ambatolaona');
insert into Cities (Id, Name) values (498, 'Třinec');
insert into Cities (Id, Name) values (499, 'Muladbucad');
insert into Cities (Id, Name) values (500, 'Cabucgayan');
insert into Cities (Id, Name) values (501, 'Sezimovo Ústí');
insert into Cities (Id, Name) values (502, 'La Paz');
insert into Cities (Id, Name) values (503, 'Jatobá');
insert into Cities (Id, Name) values (504, 'Campaka');
insert into Cities (Id, Name) values (505, 'Tatsuno');
insert into Cities (Id, Name) values (506, 'Bacelo');
insert into Cities (Id, Name) values (507, 'Sedatiagung');
insert into Cities (Id, Name) values (508, 'Sumberrejo');
insert into Cities (Id, Name) values (509, 'Táriba');
insert into Cities (Id, Name) values (510, 'Louisville');
insert into Cities (Id, Name) values (511, 'Oslo');
insert into Cities (Id, Name) values (512, 'Sudo');
insert into Cities (Id, Name) values (513, 'Memória');
insert into Cities (Id, Name) values (514, 'Grabów');
insert into Cities (Id, Name) values (515, 'Cizhu');
insert into Cities (Id, Name) values (516, 'Murun-kuren');
insert into Cities (Id, Name) values (517, 'Velyki Sorochyntsi');
insert into Cities (Id, Name) values (518, 'Rodionovo-Nesvetaiskoye');
insert into Cities (Id, Name) values (519, 'Yucheng');
insert into Cities (Id, Name) values (520, 'Laval');
insert into Cities (Id, Name) values (521, 'Celorico de Basto');
insert into Cities (Id, Name) values (522, 'Preserje pri Radomljah');
insert into Cities (Id, Name) values (523, 'Changfa');
insert into Cities (Id, Name) values (524, 'Mufulira');
insert into Cities (Id, Name) values (525, 'Cookshire-Eaton');
insert into Cities (Id, Name) values (526, 'Tëplaya Gora');
insert into Cities (Id, Name) values (527, 'Alqueva');
insert into Cities (Id, Name) values (528, 'Hassi Berkane');
insert into Cities (Id, Name) values (529, 'Huze');
insert into Cities (Id, Name) values (530, 'Arvayheer');
insert into Cities (Id, Name) values (531, 'Tayginka');
insert into Cities (Id, Name) values (532, 'Loma Bonita');
insert into Cities (Id, Name) values (533, 'Jacareí');
insert into Cities (Id, Name) values (534, 'Budrus');
insert into Cities (Id, Name) values (535, 'Asnières-sur-Seine');
insert into Cities (Id, Name) values (536, 'Shuiying');
insert into Cities (Id, Name) values (537, 'Saint-Paul');
insert into Cities (Id, Name) values (538, 'Lwówek Śląski');
insert into Cities (Id, Name) values (539, 'Guri i Zi');
insert into Cities (Id, Name) values (540, 'Qimantage');
insert into Cities (Id, Name) values (541, 'Phichit');
insert into Cities (Id, Name) values (542, 'Kelasuri');
insert into Cities (Id, Name) values (543, 'Julcamarca');
insert into Cities (Id, Name) values (544, 'Zolotonosha');
insert into Cities (Id, Name) values (545, 'Palmerston North');
insert into Cities (Id, Name) values (546, 'Zaojiacheng');
insert into Cities (Id, Name) values (547, 'Mełgiew');
insert into Cities (Id, Name) values (548, 'Wenling');
insert into Cities (Id, Name) values (549, 'Netolice');
insert into Cities (Id, Name) values (550, 'IJmuiden');
insert into Cities (Id, Name) values (551, 'Los Angeles');
insert into Cities (Id, Name) values (552, 'Sousa');
insert into Cities (Id, Name) values (553, 'Dongsheng');
insert into Cities (Id, Name) values (554, 'Rio');
insert into Cities (Id, Name) values (555, 'Teresa');
insert into Cities (Id, Name) values (556, 'Aiánteio');
insert into Cities (Id, Name) values (557, 'Campo Grande');
insert into Cities (Id, Name) values (558, 'Sirdaryo');
insert into Cities (Id, Name) values (559, 'Langsepan');
insert into Cities (Id, Name) values (560, 'Drohobych');
insert into Cities (Id, Name) values (561, 'Carregueira');
insert into Cities (Id, Name) values (562, 'Buta Ranquil');
insert into Cities (Id, Name) values (563, 'Settat');
insert into Cities (Id, Name) values (564, 'Chisec');
insert into Cities (Id, Name) values (565, 'Veliki Grđevac');
insert into Cities (Id, Name) values (566, 'Fukou');
insert into Cities (Id, Name) values (567, 'Niños Heroes');
insert into Cities (Id, Name) values (568, 'Martin');
insert into Cities (Id, Name) values (569, 'Koíla');
insert into Cities (Id, Name) values (570, 'Kamru');
insert into Cities (Id, Name) values (571, 'Ciudad Guayana');
insert into Cities (Id, Name) values (572, 'Murmuiža');
insert into Cities (Id, Name) values (573, 'Jesús Menéndez');
insert into Cities (Id, Name) values (574, 'Yalagüina');
insert into Cities (Id, Name) values (575, 'Awarawar');
insert into Cities (Id, Name) values (576, 'Ljungby');
insert into Cities (Id, Name) values (577, 'Roberval');
insert into Cities (Id, Name) values (578, 'Zengfu');
insert into Cities (Id, Name) values (579, 'Vostryakovo');
insert into Cities (Id, Name) values (580, 'Ancol');
insert into Cities (Id, Name) values (581, 'Cruz');
insert into Cities (Id, Name) values (582, 'Stockholm');
insert into Cities (Id, Name) values (583, 'Silodakon');
insert into Cities (Id, Name) values (584, 'Arjona');
insert into Cities (Id, Name) values (585, 'Bandar-e Ganāveh');
insert into Cities (Id, Name) values (586, 'Muonio');
insert into Cities (Id, Name) values (587, 'Feyẕābād');
insert into Cities (Id, Name) values (588, 'Velyka Oleksandrivka');
insert into Cities (Id, Name) values (589, 'Lugui');
insert into Cities (Id, Name) values (590, 'Al ‘Anān');
insert into Cities (Id, Name) values (591, 'Kalāt');
insert into Cities (Id, Name) values (592, 'Wonosobo');
insert into Cities (Id, Name) values (593, 'Saint-Quentin');
insert into Cities (Id, Name) values (594, 'Orocuina');
insert into Cities (Id, Name) values (595, 'Luanda');
insert into Cities (Id, Name) values (596, 'Kitakyūshū');
insert into Cities (Id, Name) values (597, 'Kalijeruk');
insert into Cities (Id, Name) values (598, 'Hekou');
insert into Cities (Id, Name) values (599, 'Wenwuba');
insert into Cities (Id, Name) values (600, 'Sulak');
insert into Cities (Id, Name) values (601, 'Guará');
insert into Cities (Id, Name) values (602, 'Terang');
insert into Cities (Id, Name) values (603, 'Bendilwungu Lor');
insert into Cities (Id, Name) values (604, 'Guder Lao');
insert into Cities (Id, Name) values (605, 'Granja');
insert into Cities (Id, Name) values (606, 'Muurla');
insert into Cities (Id, Name) values (607, 'Bantarmangu');
insert into Cities (Id, Name) values (608, 'Itaperuçu');
insert into Cities (Id, Name) values (609, 'Liuji');
insert into Cities (Id, Name) values (610, 'Colmeal');
insert into Cities (Id, Name) values (611, 'Itabirito');
insert into Cities (Id, Name) values (612, 'San Rafael');
insert into Cities (Id, Name) values (613, 'Mantang');
insert into Cities (Id, Name) values (614, 'Kuzhorskaya');
insert into Cities (Id, Name) values (615, 'Tandel');
insert into Cities (Id, Name) values (616, 'Muang Long');
insert into Cities (Id, Name) values (617, 'Shengze');
insert into Cities (Id, Name) values (618, 'Xuân Trường');
insert into Cities (Id, Name) values (619, 'Kototujuh');
insert into Cities (Id, Name) values (620, 'Angers');
insert into Cities (Id, Name) values (621, 'Hor');
insert into Cities (Id, Name) values (622, 'Concepcion');
insert into Cities (Id, Name) values (623, 'Banxi');
insert into Cities (Id, Name) values (624, 'Huangbei');
insert into Cities (Id, Name) values (625, 'Cambé');
insert into Cities (Id, Name) values (626, 'Banaran');
insert into Cities (Id, Name) values (627, 'Mar’’ina Horka');
insert into Cities (Id, Name) values (628, 'Áthyra');
insert into Cities (Id, Name) values (629, 'Kiel');
insert into Cities (Id, Name) values (630, 'Redakodi');
insert into Cities (Id, Name) values (631, 'Xia Dawo');
insert into Cities (Id, Name) values (632, 'Solkan');
insert into Cities (Id, Name) values (633, 'Muurla');
insert into Cities (Id, Name) values (634, 'Pilar');
insert into Cities (Id, Name) values (635, 'Tečovice');
insert into Cities (Id, Name) values (636, 'Qiaobian');
insert into Cities (Id, Name) values (637, 'Rongcheng');
insert into Cities (Id, Name) values (638, 'P’yŏngsŏng');
insert into Cities (Id, Name) values (639, 'Airdrie');
insert into Cities (Id, Name) values (640, 'Soure');
insert into Cities (Id, Name) values (641, 'Longxing');
insert into Cities (Id, Name) values (642, 'Arboga');
insert into Cities (Id, Name) values (643, 'Luzern');
insert into Cities (Id, Name) values (644, 'Vallecillo');
insert into Cities (Id, Name) values (645, 'Huancapi');
insert into Cities (Id, Name) values (646, 'Ancol');
insert into Cities (Id, Name) values (647, 'Dobřív');
insert into Cities (Id, Name) values (648, 'Tissa');
insert into Cities (Id, Name) values (649, 'Wujing');
insert into Cities (Id, Name) values (650, 'Muonio');
insert into Cities (Id, Name) values (651, 'Penha');
insert into Cities (Id, Name) values (652, 'Rincón');
insert into Cities (Id, Name) values (653, 'Gontar');
insert into Cities (Id, Name) values (654, 'Masuda');
insert into Cities (Id, Name) values (655, 'Tallahassee');
insert into Cities (Id, Name) values (656, 'Erie');
insert into Cities (Id, Name) values (657, 'Ōmihachiman');
insert into Cities (Id, Name) values (658, 'Khairpur');
insert into Cities (Id, Name) values (659, 'Zhaojia');
insert into Cities (Id, Name) values (660, 'Banda Layung');
insert into Cities (Id, Name) values (661, 'Asen');
insert into Cities (Id, Name) values (662, 'Muskegon');
insert into Cities (Id, Name) values (663, 'San Jose');
insert into Cities (Id, Name) values (664, 'Pangkungparuk');
insert into Cities (Id, Name) values (665, 'Sezemice');
insert into Cities (Id, Name) values (666, 'Arcueil');
insert into Cities (Id, Name) values (667, 'Taoyuan');
insert into Cities (Id, Name) values (668, 'Anling');
insert into Cities (Id, Name) values (669, 'Boevange-sur-Attert');
insert into Cities (Id, Name) values (670, 'Bengtsfors');
insert into Cities (Id, Name) values (671, 'Kapenguria');
insert into Cities (Id, Name) values (672, 'Yanagawa');
insert into Cities (Id, Name) values (673, 'Mangga Dua');
insert into Cities (Id, Name) values (674, 'Mafang');
insert into Cities (Id, Name) values (675, 'Farīdpur');
insert into Cities (Id, Name) values (676, 'Kalangan');
insert into Cities (Id, Name) values (677, 'Saint-Bruno-de-Guigues');
insert into Cities (Id, Name) values (678, 'Rybczewice');
insert into Cities (Id, Name) values (679, 'Andop');
insert into Cities (Id, Name) values (680, 'Trollhättan');
insert into Cities (Id, Name) values (681, 'Marinhais');
insert into Cities (Id, Name) values (682, 'Partikan');
insert into Cities (Id, Name) values (683, 'Cam Lộ');
insert into Cities (Id, Name) values (684, 'Oslo');
insert into Cities (Id, Name) values (685, 'Casais Baleal');
insert into Cities (Id, Name) values (686, 'Montceau-les-Mines');
insert into Cities (Id, Name) values (687, 'Bayshint');
insert into Cities (Id, Name) values (688, 'Tarusan');
insert into Cities (Id, Name) values (689, 'Custódia');
insert into Cities (Id, Name) values (690, 'Muravlenko');
insert into Cities (Id, Name) values (691, 'Luopu');
insert into Cities (Id, Name) values (692, 'Francistown');
insert into Cities (Id, Name) values (693, 'Årsta');
insert into Cities (Id, Name) values (694, 'Łaziska Górne');
insert into Cities (Id, Name) values (695, 'San Fernando');
insert into Cities (Id, Name) values (696, 'Kuantan');
insert into Cities (Id, Name) values (697, 'Paris 02');
insert into Cities (Id, Name) values (698, 'Sibulan');
insert into Cities (Id, Name) values (699, 'Athens');
insert into Cities (Id, Name) values (700, 'Jinchang');
insert into Cities (Id, Name) values (701, 'Yanping');
insert into Cities (Id, Name) values (702, 'Nanling');
insert into Cities (Id, Name) values (703, 'Ngondokandawu');
insert into Cities (Id, Name) values (704, 'Hetoudian');
insert into Cities (Id, Name) values (705, 'Huotong');
insert into Cities (Id, Name) values (706, 'Donghui');
insert into Cities (Id, Name) values (707, 'Hongcheng');
insert into Cities (Id, Name) values (708, 'Svetlanovskiy');
insert into Cities (Id, Name) values (709, 'Kemendung');
insert into Cities (Id, Name) values (710, 'Severoural’sk');
insert into Cities (Id, Name) values (711, 'Palampal');
insert into Cities (Id, Name) values (712, 'Al Mukallā');
insert into Cities (Id, Name) values (713, 'Iznoski');
insert into Cities (Id, Name) values (714, 'Maganha');
insert into Cities (Id, Name) values (715, 'Kapasan');
insert into Cities (Id, Name) values (716, 'Banquero');
insert into Cities (Id, Name) values (717, 'Klerksdorp');
insert into Cities (Id, Name) values (718, 'São Tomé');
insert into Cities (Id, Name) values (719, 'Binhe');
insert into Cities (Id, Name) values (720, 'Patrída');
insert into Cities (Id, Name) values (721, 'Uiasa');
insert into Cities (Id, Name) values (722, 'San Felipe');
insert into Cities (Id, Name) values (723, 'Richmond');
insert into Cities (Id, Name) values (724, 'Huaping');
insert into Cities (Id, Name) values (725, 'Tours');
insert into Cities (Id, Name) values (726, 'Adygeysk');
insert into Cities (Id, Name) values (727, 'Rancabungur');
insert into Cities (Id, Name) values (728, 'Orange Walk');
insert into Cities (Id, Name) values (729, 'Sovetsk');
insert into Cities (Id, Name) values (730, 'Kota Bharu');
insert into Cities (Id, Name) values (731, 'Repentigny');
insert into Cities (Id, Name) values (732, 'Nazran’');
insert into Cities (Id, Name) values (733, 'Gyumri');
insert into Cities (Id, Name) values (734, 'Codajás');
insert into Cities (Id, Name) values (735, 'Tanahwangko');
insert into Cities (Id, Name) values (736, 'Hasuda');
insert into Cities (Id, Name) values (737, 'Taling');
insert into Cities (Id, Name) values (738, 'Warudoyong');
insert into Cities (Id, Name) values (739, 'Dedza');
insert into Cities (Id, Name) values (740, 'Proletarsk');
insert into Cities (Id, Name) values (741, 'Kungsbacka');
insert into Cities (Id, Name) values (742, 'Sioguí Abajo');
insert into Cities (Id, Name) values (743, 'Tyshkivka');
insert into Cities (Id, Name) values (744, 'Wolanów');
insert into Cities (Id, Name) values (745, 'Sugiharjo');
insert into Cities (Id, Name) values (746, 'Kristinehamn');
insert into Cities (Id, Name) values (747, 'Al ‘Ashshah');
insert into Cities (Id, Name) values (748, 'Hobart');
insert into Cities (Id, Name) values (749, 'Jiannan');
insert into Cities (Id, Name) values (750, 'Amirabad');
insert into Cities (Id, Name) values (751, 'Lebyazh’ye');
insert into Cities (Id, Name) values (752, 'Bistrica pri Tržiču');
insert into Cities (Id, Name) values (753, 'Iguatu');
insert into Cities (Id, Name) values (754, 'Brusque');
insert into Cities (Id, Name) values (755, 'Simpang');
insert into Cities (Id, Name) values (756, 'Malausma Kidul');
insert into Cities (Id, Name) values (757, 'Chitagá');
insert into Cities (Id, Name) values (758, 'Bayt ‘Īnūn');
insert into Cities (Id, Name) values (759, 'Stockholm');
insert into Cities (Id, Name) values (760, 'Marneuli');
insert into Cities (Id, Name) values (761, 'Uścimów Stary');
insert into Cities (Id, Name) values (762, 'Guojiaba');
insert into Cities (Id, Name) values (763, 'Khemarat');
insert into Cities (Id, Name) values (764, 'Sitovo');
insert into Cities (Id, Name) values (765, 'Nangang');
insert into Cities (Id, Name) values (766, 'Shāhīn Dezh');
insert into Cities (Id, Name) values (767, 'Maxixe');
insert into Cities (Id, Name) values (768, 'Batangan');
insert into Cities (Id, Name) values (769, 'Zhaoguli');
insert into Cities (Id, Name) values (770, 'Pulo');
insert into Cities (Id, Name) values (771, 'Kemiri Daya');
insert into Cities (Id, Name) values (772, 'Akoupé');
insert into Cities (Id, Name) values (773, 'Młynary');
insert into Cities (Id, Name) values (774, 'Богданци');
insert into Cities (Id, Name) values (775, 'Ghauspur');
insert into Cities (Id, Name) values (776, 'Begejci');
insert into Cities (Id, Name) values (777, 'Nishiwaki');
insert into Cities (Id, Name) values (778, 'Skuhrov nad Bělou');
insert into Cities (Id, Name) values (779, 'Sirājganj');
insert into Cities (Id, Name) values (780, 'Palestina');
insert into Cities (Id, Name) values (781, 'Kaduengang');
insert into Cities (Id, Name) values (782, 'Falefa');
insert into Cities (Id, Name) values (783, 'Kalangala');
insert into Cities (Id, Name) values (784, 'Berezniki');
insert into Cities (Id, Name) values (785, 'Cochrane');
insert into Cities (Id, Name) values (786, 'Huaribamba');
insert into Cities (Id, Name) values (787, 'Xuji');
insert into Cities (Id, Name) values (788, 'Sambava');
insert into Cities (Id, Name) values (789, 'La Maná');
insert into Cities (Id, Name) values (790, 'Gelang');
insert into Cities (Id, Name) values (791, 'Liupai');
insert into Cities (Id, Name) values (792, 'Ráquira');
insert into Cities (Id, Name) values (793, 'Gunungjulang');
insert into Cities (Id, Name) values (794, 'Sölvesborg');
insert into Cities (Id, Name) values (795, 'Claveria');
insert into Cities (Id, Name) values (796, 'Madang');
insert into Cities (Id, Name) values (797, 'Kebonan');
insert into Cities (Id, Name) values (798, 'Wan’an');
insert into Cities (Id, Name) values (799, 'Miami');
insert into Cities (Id, Name) values (800, 'Talipan');
insert into Cities (Id, Name) values (801, 'Fuwen');
insert into Cities (Id, Name) values (802, 'Valle San Francisco');
insert into Cities (Id, Name) values (803, 'Dzhetygara');
insert into Cities (Id, Name) values (804, 'Bakov nad Jizerou');
insert into Cities (Id, Name) values (805, 'Chengxiang');
insert into Cities (Id, Name) values (806, 'Alannay');
insert into Cities (Id, Name) values (807, 'Taozixi');
insert into Cities (Id, Name) values (808, 'Bokoro');
insert into Cities (Id, Name) values (809, 'Lages');
insert into Cities (Id, Name) values (810, 'Kertosari');
insert into Cities (Id, Name) values (811, 'Galūgāh');
insert into Cities (Id, Name) values (812, 'Neundeut');
insert into Cities (Id, Name) values (813, 'Slobodskoy');
insert into Cities (Id, Name) values (814, 'Dobra');
insert into Cities (Id, Name) values (815, 'Leping');
insert into Cities (Id, Name) values (816, 'Panyuran');
insert into Cities (Id, Name) values (817, 'Kuala Lumpur');
insert into Cities (Id, Name) values (818, 'Saint Petersburg');
insert into Cities (Id, Name) values (819, 'Stare Juchy');
insert into Cities (Id, Name) values (820, 'Shumikhinskiy');
insert into Cities (Id, Name) values (821, 'Dakoro');
insert into Cities (Id, Name) values (822, 'Kävlinge');
insert into Cities (Id, Name) values (823, 'San Juan');
insert into Cities (Id, Name) values (824, 'Káto Miliá');
insert into Cities (Id, Name) values (825, 'Tielong');
insert into Cities (Id, Name) values (826, 'Pátmos');
insert into Cities (Id, Name) values (827, 'Begang');
insert into Cities (Id, Name) values (828, 'Poitiers');
insert into Cities (Id, Name) values (829, 'Al Marsá');
insert into Cities (Id, Name) values (830, 'Västerås');
insert into Cities (Id, Name) values (831, 'Maqiu');
insert into Cities (Id, Name) values (832, 'Khao Khitchakut');
insert into Cities (Id, Name) values (833, 'Ku‘aydinah');
insert into Cities (Id, Name) values (834, 'Abashiri');
insert into Cities (Id, Name) values (835, 'Lalmanirhat');
insert into Cities (Id, Name) values (836, 'Phra Phutthabat');
insert into Cities (Id, Name) values (837, 'Vetlanda');
insert into Cities (Id, Name) values (838, 'Ankazobe');
insert into Cities (Id, Name) values (839, 'Ngromo');
insert into Cities (Id, Name) values (840, 'Ordzhonikidze');
insert into Cities (Id, Name) values (841, 'Oematnunu');
insert into Cities (Id, Name) values (842, 'San Isidro');
insert into Cities (Id, Name) values (843, 'Ngandangan');
insert into Cities (Id, Name) values (844, 'Sablé-sur-Sarthe');
insert into Cities (Id, Name) values (845, 'Larkird');
insert into Cities (Id, Name) values (846, 'Wailang');
insert into Cities (Id, Name) values (847, 'San Esteban');
insert into Cities (Id, Name) values (848, 'Liugong');
insert into Cities (Id, Name) values (849, 'Emiliano Zapata');
insert into Cities (Id, Name) values (850, 'Maindang');
insert into Cities (Id, Name) values (851, 'Paderne');
insert into Cities (Id, Name) values (852, 'Ar Ruḩaybah');
insert into Cities (Id, Name) values (853, 'Kombolcha');
insert into Cities (Id, Name) values (854, 'Morshansk');
insert into Cities (Id, Name) values (855, 'Qianjin');
insert into Cities (Id, Name) values (856, 'Casais');
insert into Cities (Id, Name) values (857, 'Nagosela');
insert into Cities (Id, Name) values (858, 'Dejilin');
insert into Cities (Id, Name) values (859, 'Mata');
insert into Cities (Id, Name) values (860, 'Cigebrok');
insert into Cities (Id, Name) values (861, 'Caxambu');
insert into Cities (Id, Name) values (862, 'Batiano');
insert into Cities (Id, Name) values (863, 'Malawa');
insert into Cities (Id, Name) values (864, 'Far‘ūn');
insert into Cities (Id, Name) values (865, 'Batasan Bata');
insert into Cities (Id, Name) values (866, 'Cinyasag');
insert into Cities (Id, Name) values (867, 'Akarakar');
insert into Cities (Id, Name) values (868, 'Ipuh');
insert into Cities (Id, Name) values (869, 'Porangaba');
insert into Cities (Id, Name) values (870, 'Damai');
insert into Cities (Id, Name) values (871, 'Jiaqu');
insert into Cities (Id, Name) values (872, 'Zhizhong');
insert into Cities (Id, Name) values (873, 'Nūbā');
insert into Cities (Id, Name) values (874, 'Bizhbulyak');
insert into Cities (Id, Name) values (875, 'Jinshan');
insert into Cities (Id, Name) values (876, 'Ariana');
insert into Cities (Id, Name) values (877, 'Lyntupy');
insert into Cities (Id, Name) values (878, 'Banawang');
insert into Cities (Id, Name) values (879, 'Vilar');
insert into Cities (Id, Name) values (880, 'Khánh Hải');
insert into Cities (Id, Name) values (881, 'Penaraga');
insert into Cities (Id, Name) values (882, 'Garanhuns');
insert into Cities (Id, Name) values (883, 'Lahān');
insert into Cities (Id, Name) values (884, 'Qingzhou');
insert into Cities (Id, Name) values (885, 'Kota Ternate');
insert into Cities (Id, Name) values (886, 'Rymanów');
insert into Cities (Id, Name) values (887, 'Nowe');
insert into Cities (Id, Name) values (888, 'Wojcieszków');
insert into Cities (Id, Name) values (889, 'Piškorevci');
insert into Cities (Id, Name) values (890, 'Alíartos');
insert into Cities (Id, Name) values (891, 'Herrán');
insert into Cities (Id, Name) values (892, 'Koronadal');
insert into Cities (Id, Name) values (893, 'Velika');
insert into Cities (Id, Name) values (894, 'Bīrganj');
insert into Cities (Id, Name) values (895, 'Muladbucad');
insert into Cities (Id, Name) values (896, 'Chitral');
insert into Cities (Id, Name) values (897, 'San Basilio');
insert into Cities (Id, Name) values (898, 'Bernardo de Irigoyen');
insert into Cities (Id, Name) values (899, 'Solna');
insert into Cities (Id, Name) values (900, 'Lago');
insert into Cities (Id, Name) values (901, 'Pskov');
insert into Cities (Id, Name) values (902, 'Petřvald');
insert into Cities (Id, Name) values (903, 'Payao');
insert into Cities (Id, Name) values (904, 'Wootton');
insert into Cities (Id, Name) values (905, 'Xinjia');
insert into Cities (Id, Name) values (906, 'Labo');
insert into Cities (Id, Name) values (907, 'Gračanica');
insert into Cities (Id, Name) values (908, 'Bayt Sīrā');
insert into Cities (Id, Name) values (909, 'Tohautu');
insert into Cities (Id, Name) values (910, 'Magitang');
insert into Cities (Id, Name) values (911, 'Guanjiabao');
insert into Cities (Id, Name) values (912, 'Iwata');
insert into Cities (Id, Name) values (913, 'Liushun');
insert into Cities (Id, Name) values (914, 'Jiefangyan');
insert into Cities (Id, Name) values (915, 'Kuching');
insert into Cities (Id, Name) values (916, 'Izazi');
insert into Cities (Id, Name) values (917, 'Mangero');
insert into Cities (Id, Name) values (918, 'Morazán');
insert into Cities (Id, Name) values (919, 'Jamao al Norte');
insert into Cities (Id, Name) values (920, 'Luodian');
insert into Cities (Id, Name) values (921, 'Dakhla');
insert into Cities (Id, Name) values (922, 'Kantemirovka');
insert into Cities (Id, Name) values (923, 'Velká nad Veličkou');
insert into Cities (Id, Name) values (924, 'Arboga');
insert into Cities (Id, Name) values (925, 'Ayia Napa');
insert into Cities (Id, Name) values (926, 'Radenka');
insert into Cities (Id, Name) values (927, 'Ulyanovsk');
insert into Cities (Id, Name) values (928, 'Kurlovo');
insert into Cities (Id, Name) values (929, 'Azua');
insert into Cities (Id, Name) values (930, 'Bojonghaur');
insert into Cities (Id, Name) values (931, 'Armenokhórion');
insert into Cities (Id, Name) values (932, 'Elverum');
insert into Cities (Id, Name) values (933, 'Bužim');
insert into Cities (Id, Name) values (934, 'Kuala Lumpur');
insert into Cities (Id, Name) values (935, 'Gayam');
insert into Cities (Id, Name) values (936, 'Kinalansan');
insert into Cities (Id, Name) values (937, 'Lubāna');
insert into Cities (Id, Name) values (938, 'Mānānwāla');
insert into Cities (Id, Name) values (939, 'Tempe');
insert into Cities (Id, Name) values (940, 'Armenia');
insert into Cities (Id, Name) values (941, 'Machida');
insert into Cities (Id, Name) values (942, 'Priargunsk');
insert into Cities (Id, Name) values (943, 'Belisario Dominguez');
insert into Cities (Id, Name) values (944, 'Liberia');
insert into Cities (Id, Name) values (945, 'Manjakandriana');
insert into Cities (Id, Name) values (946, 'Bastos');
insert into Cities (Id, Name) values (947, 'Böhöt');
insert into Cities (Id, Name) values (948, 'Basing');
insert into Cities (Id, Name) values (949, 'Horní Cerekev');
insert into Cities (Id, Name) values (950, 'Santa Cruz do Rio Pardo');
insert into Cities (Id, Name) values (951, 'Kadumelati');
insert into Cities (Id, Name) values (952, 'Narew');
insert into Cities (Id, Name) values (953, 'Muyi');
insert into Cities (Id, Name) values (954, 'Hengshi');
insert into Cities (Id, Name) values (955, 'Tabaga');
insert into Cities (Id, Name) values (956, 'Nong Bua Lamphu');
insert into Cities (Id, Name) values (957, 'Gaibei');
insert into Cities (Id, Name) values (958, 'Ozërsk');
insert into Cities (Id, Name) values (959, 'Pujijie');
insert into Cities (Id, Name) values (960, 'Kaparéllion');
insert into Cities (Id, Name) values (961, 'Acaraú');
insert into Cities (Id, Name) values (962, 'Chengxi');
insert into Cities (Id, Name) values (963, 'Canedo');
insert into Cities (Id, Name) values (964, 'Tarikolot');
insert into Cities (Id, Name) values (965, 'Maoming');
insert into Cities (Id, Name) values (966, 'Laohekou');
insert into Cities (Id, Name) values (967, 'Ciawi');
insert into Cities (Id, Name) values (968, 'Tinghir');
insert into Cities (Id, Name) values (969, 'Östersund');
insert into Cities (Id, Name) values (970, 'Leicheng');
insert into Cities (Id, Name) values (971, 'Eusebio Ayala');
insert into Cities (Id, Name) values (972, 'Federal');
insert into Cities (Id, Name) values (973, 'Zhongguan');
insert into Cities (Id, Name) values (974, 'La Tola');
insert into Cities (Id, Name) values (975, 'Kekeran');
insert into Cities (Id, Name) values (976, 'San Juan');
insert into Cities (Id, Name) values (977, 'Facatativá');
insert into Cities (Id, Name) values (978, 'Nova Iguaçu');
insert into Cities (Id, Name) values (979, 'Calais');
insert into Cities (Id, Name) values (980, 'Cumaná');
insert into Cities (Id, Name) values (981, 'El Aguacate');
insert into Cities (Id, Name) values (982, 'Krajan Karanganyar');
insert into Cities (Id, Name) values (983, 'Labuan');
insert into Cities (Id, Name) values (984, 'Labuhan');
insert into Cities (Id, Name) values (985, 'Daojiang');
insert into Cities (Id, Name) values (986, 'Novodvinsk');
insert into Cities (Id, Name) values (987, 'Longhe');
insert into Cities (Id, Name) values (988, 'Bulacan');
insert into Cities (Id, Name) values (989, 'El Carmen');
insert into Cities (Id, Name) values (990, 'Kolwezi');
insert into Cities (Id, Name) values (991, 'Bājitpur');
insert into Cities (Id, Name) values (992, 'Shangpai');
insert into Cities (Id, Name) values (993, 'Baokou');
insert into Cities (Id, Name) values (994, 'Yishui');
insert into Cities (Id, Name) values (995, 'Saint-Bruno-de-Montarville');
insert into Cities (Id, Name) values (996, 'Tubod');
insert into Cities (Id, Name) values (997, 'Xiagong');
insert into Cities (Id, Name) values (998, 'Pidvynohradiv');
insert into Cities (Id, Name) values (999, 'Trikora');
insert into Cities (Id, Name) values (1000, 'Yacheng');
