insert into Countrys (Id, Name) values (1, 'Finland');
insert into Countrys (Id, Name) values (2, 'Morocco');
insert into Countrys (Id, Name) values (3, 'Finland');
insert into Countrys (Id, Name) values (4, 'Burkina Faso');
insert into Countrys (Id, Name) values (5, 'Tunisia');
insert into Countrys (Id, Name) values (6, 'Indonesia');
insert into Countrys (Id, Name) values (7, 'Brazil');
insert into Countrys (Id, Name) values (8, 'China');
insert into Countrys (Id, Name) values (9, 'Uganda');
insert into Countrys (Id, Name) values (10, 'Philippines');
insert into Countrys (Id, Name) values (11, 'Colombia');
insert into Countrys (Id, Name) values (12, 'Qatar');
insert into Countrys (Id, Name) values (13, 'Haiti');
insert into Countrys (Id, Name) values (14, 'Poland');
insert into Countrys (Id, Name) values (15, 'Cuba');
insert into Countrys (Id, Name) values (16, 'Portugal');
insert into Countrys (Id, Name) values (17, 'France');
insert into Countrys (Id, Name) values (18, 'Philippines');
insert into Countrys (Id, Name) values (19, 'China');
insert into Countrys (Id, Name) values (20, 'China');
insert into Countrys (Id, Name) values (21, 'Mauritius');
insert into Countrys (Id, Name) values (22, 'United States');
insert into Countrys (Id, Name) values (23, 'Poland');
insert into Countrys (Id, Name) values (24, 'Thailand');
insert into Countrys (Id, Name) values (25, 'Bosnia and Herzegovina');
insert into Countrys (Id, Name) values (26, 'Portugal');
insert into Countrys (Id, Name) values (27, 'China');
insert into Countrys (Id, Name) values (28, 'China');
insert into Countrys (Id, Name) values (29, 'Iran');
insert into Countrys (Id, Name) values (30, 'Costa Rica');
insert into Countrys (Id, Name) values (31, 'Guinea');
insert into Countrys (Id, Name) values (32, 'Russia');
insert into Countrys (Id, Name) values (33, 'Macedonia');
insert into Countrys (Id, Name) values (34, 'Poland');
insert into Countrys (Id, Name) values (35, 'China');
insert into Countrys (Id, Name) values (36, 'South Korea');
insert into Countrys (Id, Name) values (37, 'Portugal');
insert into Countrys (Id, Name) values (38, 'China');
insert into Countrys (Id, Name) values (39, 'Brazil');
insert into Countrys (Id, Name) values (40, 'Russia');
insert into Countrys (Id, Name) values (41, 'Brazil');
insert into Countrys (Id, Name) values (42, 'Guatemala');
insert into Countrys (Id, Name) values (43, 'Philippines');
insert into Countrys (Id, Name) values (44, 'Brazil');
insert into Countrys (Id, Name) values (45, 'Peru');
insert into Countrys (Id, Name) values (46, 'China');
insert into Countrys (Id, Name) values (47, 'Libya');
insert into Countrys (Id, Name) values (48, 'Afghanistan');
insert into Countrys (Id, Name) values (49, 'China');
insert into Countrys (Id, Name) values (50, 'Philippines');
insert into Countrys (Id, Name) values (51, 'Costa Rica');
insert into Countrys (Id, Name) values (52, 'China');
insert into Countrys (Id, Name) values (53, 'China');
insert into Countrys (Id, Name) values (54, 'Philippines');
insert into Countrys (Id, Name) values (55, 'China');
insert into Countrys (Id, Name) values (56, 'Russia');
insert into Countrys (Id, Name) values (57, 'Russia');
insert into Countrys (Id, Name) values (58, 'Portugal');
insert into Countrys (Id, Name) values (59, 'France');
insert into Countrys (Id, Name) values (60, 'Serbia');
insert into Countrys (Id, Name) values (61, 'Poland');
insert into Countrys (Id, Name) values (62, 'Indonesia');
insert into Countrys (Id, Name) values (63, 'China');
insert into Countrys (Id, Name) values (64, 'Ukraine');
insert into Countrys (Id, Name) values (65, 'China');
insert into Countrys (Id, Name) values (66, 'New Caledonia');
insert into Countrys (Id, Name) values (67, 'Argentina');
insert into Countrys (Id, Name) values (68, 'United States');
insert into Countrys (Id, Name) values (69, 'Ethiopia');
insert into Countrys (Id, Name) values (70, 'Finland');
insert into Countrys (Id, Name) values (71, 'Botswana');
insert into Countrys (Id, Name) values (72, 'Nigeria');
insert into Countrys (Id, Name) values (73, 'China');
insert into Countrys (Id, Name) values (74, 'Czech Republic');
insert into Countrys (Id, Name) values (75, 'Philippines');
insert into Countrys (Id, Name) values (76, 'Bangladesh');
insert into Countrys (Id, Name) values (77, 'Indonesia');
insert into Countrys (Id, Name) values (78, 'Brazil');
insert into Countrys (Id, Name) values (79, 'China');
insert into Countrys (Id, Name) values (80, 'China');
insert into Countrys (Id, Name) values (81, 'Russia');
insert into Countrys (Id, Name) values (82, 'China');
insert into Countrys (Id, Name) values (83, 'Ukraine');
insert into Countrys (Id, Name) values (84, 'China');
insert into Countrys (Id, Name) values (85, 'Cameroon');
insert into Countrys (Id, Name) values (86, 'Kazakhstan');
insert into Countrys (Id, Name) values (87, 'Sweden');
insert into Countrys (Id, Name) values (88, 'Argentina');
insert into Countrys (Id, Name) values (89, 'Indonesia');
insert into Countrys (Id, Name) values (90, 'Thailand');
insert into Countrys (Id, Name) values (91, 'Russia');
insert into Countrys (Id, Name) values (92, 'Guatemala');
insert into Countrys (Id, Name) values (93, 'Poland');
insert into Countrys (Id, Name) values (94, 'China');
insert into Countrys (Id, Name) values (95, 'Colombia');
insert into Countrys (Id, Name) values (96, 'Colombia');
insert into Countrys (Id, Name) values (97, 'Namibia');
insert into Countrys (Id, Name) values (98, 'Czech Republic');
insert into Countrys (Id, Name) values (99, 'Portugal');
insert into Countrys (Id, Name) values (100, 'Norway');
