insert into Countries (Name) values ('Ireland');
insert into Countries (Name) values ('United States');
insert into Countries (Name) values ('Czech Republic');
insert into Countries (Name) values ('China');
insert into Countries (Name) values ('Indonesia');
insert into Countries (Name) values ('Poland');
insert into Countries (Name) values ('Japan');
insert into Countries (Name) values ('France');
insert into Countries (Name) values ('Hungary');
insert into Countries (Name) values ('Brazil');
insert into Countries (Name) values ('United States');
insert into Countries (Name) values ('Zambia');
insert into Countries (Name) values ('China');
insert into Countries (Name) values ('Argentina');
insert into Countries (Name) values ('Brazil');
insert into Countries (Name) values ('Brazil');
insert into Countries (Name) values ('Montenegro');
insert into Countries (Name) values ('Peru');
insert into Countries (Name) values ('Indonesia');
insert into Countries (Name) values ('Tanzania');
insert into Countries (Name) values ('Poland');
insert into Countries (Name) values ('France');
insert into Countries (Name) values ('Argentina');
insert into Countries (Name) values ('United Arab Emirates');
insert into Countries (Name) values ('Philippines');
insert into Countries (Name) values ('South Korea');
insert into Countries (Name) values ('China');
insert into Countries (Name) values ('Sweden');
insert into Countries (Name) values ('United States');
insert into Countries (Name) values ('China');
insert into Countries (Name) values ('Philippines');
insert into Countries (Name) values ('Canada');
insert into Countries (Name) values ('China');
insert into Countries (Name) values ('Peru');
insert into Countries (Name) values ('Albania');
insert into Countries (Name) values ('China');
insert into Countries (Name) values ('Brazil');
insert into Countries (Name) values ('Tajikistan');
insert into Countries (Name) values ('Albania');
insert into Countries (Name) values ('Poland');
insert into Countries (Name) values ('Armenia');
insert into Countries (Name) values ('China');
insert into Countries (Name) values ('Indonesia');
insert into Countries (Name) values ('Indonesia');
insert into Countries (Name) values ('China');
insert into Countries (Name) values ('Thailand');
insert into Countries (Name) values ('China');
insert into Countries (Name) values ('Mayotte');
insert into Countries (Name) values ('Mexico');
insert into Countries (Name) values ('Russia');
