insert into Streets (Name) values ('Khreshchatyk');
insert into Streets (Name) values ('Shevchenka');
insert into Streets (Name) values ('Franka');
insert into Streets (Name) values ('Hrushevskoho');
insert into Streets (Name) values ('Sadova');
insert into Streets (Name) values ('Marszalkowska');
insert into Streets (Name) values ('Dluga');
insert into Streets (Name) values ('Piotrkowska');
insert into Streets (Name) values ('Florianska');
insert into Streets (Name) values ('Krakowska');
insert into Streets (Name) values ('Hauptstrasse');
insert into Streets (Name) values ('Bahnhofstrasse');
insert into Streets (Name) values ('Schillerstrasse');
insert into Streets (Name) values ('Goethestrasse');
insert into Streets (Name) values ('Lindenallee');
insert into Streets (Name) values ('Rue de la Paix');
insert into Streets (Name) values ('Avenue Victor Hugo');
insert into Streets (Name) values ('Rue Saint-Denis');
insert into Streets (Name) values ('Boulevard Voltaire');
insert into Streets (Name) values ('Rue des Lilas');
insert into Streets (Name) values ('Calle Mayor');
insert into Streets (Name) values ('Gran Via');
insert into Streets (Name) values ('Calle de Alcala');
insert into Streets (Name) values ('Paseo del Prado');
insert into Streets (Name) values ('Rambla Nova');
insert into Streets (Name) values ('Via Roma');
insert into Streets (Name) values ('Via Garibaldi');
insert into Streets (Name) values ('Corso Buenos Aires');
insert into Streets (Name) values ('Via Dante');
insert into Streets (Name) values ('Via Manzoni');
insert into Streets (Name) values ('Kalverstraat');
insert into Streets (Name) values ('Damrak');
insert into Streets (Name) values ('Prinsengracht');
insert into Streets (Name) values ('Coolsingel');
insert into Streets (Name) values ('Oudegracht');
insert into Streets (Name) values ('Vaclavske namesti');
insert into Streets (Name) values ('Parizska');
insert into Streets (Name) values ('Narodni');
insert into Streets (Name) values ('Masarykova');
insert into Streets (Name) values ('Ceska');
insert into Streets (Name) values ('High Street');
insert into Streets (Name) values ('Baker Street');
insert into Streets (Name) values ('Kings Road');
insert into Streets (Name) values ('Victoria Street');
insert into Streets (Name) values ('Queens Road');
insert into Streets (Name) values ('Grafton Street');
insert into Streets (Name) values ('O Connell Street');
insert into Streets (Name) values ('Patrick Street');
insert into Streets (Name) values ('Shop Street');
insert into Streets (Name) values ('Drottninggatan');
insert into Streets (Name) values ('Kungsgatan');
insert into Streets (Name) values ('Storgatan');
insert into Streets (Name) values ('Vasagatan');
insert into Streets (Name) values ('Karl Johans gate');
insert into Streets (Name) values ('Storgata');
insert into Streets (Name) values ('Bryggen');
insert into Streets (Name) values ('Kirkegata');
insert into Streets (Name) values ('Rua Augusta');
insert into Streets (Name) values ('Avenida da Liberdade');
insert into Streets (Name) values ('Rua de Santa Catarina');
insert into Streets (Name) values ('Rua do Carmo');
insert into Streets (Name) values ('Karntner Strasse');
insert into Streets (Name) values ('Mariahilfer Strasse');
insert into Streets (Name) values ('Getreidegasse');
insert into Streets (Name) values ('Landstrasse');
insert into Streets (Name) values ('Andrassy ut');
insert into Streets (Name) values ('Vaci utca');
insert into Streets (Name) values ('Rakoczi ut');
insert into Streets (Name) values ('Kossuth ter');
